// Source snapshots for this preview only. No service handlers are imported.
export const groups = [
  { id: "compact", name: "01 / Compact", range: "32–38px", padding: "x 12 / y 4–6px", radius: "12px / pill", use: "항목 편집·완료, 작은 헤더 액션", reason: "py-1 ~ py-1.5의 짧은 세로 여백을 공유합니다. 아이콘은 32–36px 정사각형입니다.", height: 36, px: 12, font: 13, r: 12 },
  { id: "regular", name: "02 / Regular", range: "40–44px", padding: "x 12–16 / y 8–10px", radius: "12–14px / pill", use: "자료 업로드, 메뉴 항목, 파일 선택", reason: "py-2 중심의 일반 액션입니다. 메뉴 행의 py-2.5와 44px 아이콘도 이 구간에 속합니다.", height: 40, px: 16, font: 14, r: 14 },
  { id: "form", name: "03 / Spacious", range: "48–50px", padding: "x 16 / y 12px", radius: "14–16px", use: "할 일 추가, 저장·취소, 모달 확인·삭제", reason: "py-3를 공유합니다. 같은 높이에 primary, secondary, danger가 모두 존재합니다.", height: 48, px: 16, font: 14, r: 14 },
  { id: "tall", name: "04 / Tall", range: "56–58px", padding: "x 16 / y 16px", radius: "18px", use: "로그인, 계속하기, 계정 바꾸기", reason: "로그인 화면의 py-4 패턴입니다. Spacious보다 실제 높이가 8px 더 커 별도 관찰 그룹으로 둡니다.", height: 56, px: 16, font: 16, r: 18 },
] as const;

export type GroupId = (typeof groups)[number]["id"];
export type Sample = {
  id: string; group: GroupId; label: string; role: string; source: string;
  location: string; width: string; declaredFont: string; className: string;
  icon?: "dots" | "close" | "send";
};

export const samples: Sample[] = [
  { id: "edit", group: "compact", label: "수정", role: "secondary", source: "src/components/plan-screen.tsx:761", location: "계획 / 개인 할 일 항목", width: "content", declaredFont: "12px / 600", className: "rounded-full border border-slate-200 bg-white px-3 py-1 text-xs font-semibold text-slate-600" },
  { id: "complete", group: "compact", label: "완료", role: "강조 / dark", source: "src/components/plan-screen.tsx:770", location: "계획 / 미완료 할 일", width: "content", declaredFont: "12px / 600", className: "rounded-full px-3 py-1 text-xs font-semibold bg-slate-950 text-white" },
  { id: "image", group: "compact", label: "이미지 추가", role: "secondary", source: "src/components/plan-screen.tsx:458", location: "계획 / 자료 헤더", width: "content", declaredFont: "12px / 600", className: "rounded-[12px] border border-slate-200 bg-white px-3 py-1.5 text-xs font-semibold text-slate-700 shadow-[0_4px_10px_rgba(15,23,42,0.03)]" },
  { id: "rules", group: "compact", label: "수정하기", role: "secondary / brand", source: "src/components/study-rules-modal.tsx:67", location: "스터디 규칙 / 헤더", width: "content, shrink-0", declaredFont: "13px / 600", className: "shrink-0 rounded-full border border-slate-200 px-3 py-1.5 text-[13px] font-semibold text-[var(--brand)]" },
  { id: "delete-icon", group: "compact", label: "자료 삭제", role: "danger / ghost", source: "src/components/materials-screen.tsx:451", location: "자료 / 카드 우측", width: "icon: 32px", declaredFont: "아이콘 16px", icon: "close", className: "rounded-full p-2 text-rose-300 transition hover:bg-rose-50 hover:text-rose-600" },
  { id: "more", group: "compact", label: "자료 메뉴", role: "ghost", source: "src/components/materials-screen.tsx:461", location: "자료 / 카드 우측", width: "icon: 36px", declaredFont: "아이콘 20px", icon: "dots", className: "rounded-full p-2 text-slate-400 transition hover:bg-slate-100 hover:text-slate-700" },
  { id: "upload", group: "regular", label: "+ 자료 업로드", role: "primary", source: "src/components/materials-screen.tsx:896", location: "자료 / 페이지 상단", width: "content", declaredFont: "12px / 600", className: "rounded-full bg-[#4CAF7A] px-4 py-2 text-xs font-semibold text-white shadow-[0_12px_24px_rgba(76,175,122,0.22)] transition hover:brightness-105" },
  { id: "file", group: "regular", label: "파일 선택", role: "primary", source: "src/components/materials-screen.tsx:921", location: "자료 / 업로드 패널", width: "content", declaredFont: "14px / 600", className: "rounded-full bg-[#4CAF7A] px-4 py-2 text-sm font-semibold text-white transition hover:brightness-105 disabled:opacity-50" },
  { id: "close", group: "regular", label: "닫기", role: "secondary", source: "src/components/materials-screen.tsx:928", location: "자료 / 업로드 패널", width: "content", declaredFont: "14px / 600", className: "rounded-full border border-slate-200 bg-white px-4 py-2 text-sm font-semibold text-slate-600 transition hover:border-slate-300 hover:text-slate-900" },
  { id: "ai", group: "regular", label: "AI로 열기", role: "ghost", source: "src/components/materials-screen.tsx:472", location: "자료 / 드롭다운 메뉴", width: "full / 메뉴 너비", declaredFont: "14px / 500", className: "block w-full rounded-[14px] px-3 py-2 text-left text-sm font-medium text-slate-700 transition hover:bg-slate-50" },
  { id: "send", group: "regular", label: "질문 보내기", role: "primary", source: "src/components/materials-screen.tsx:612", location: "자료 / AI 입력창", width: "icon: 44px", declaredFont: "아이콘 20px", icon: "send", className: "flex h-11 w-11 items-center justify-center rounded-full bg-[#4CAF7A] text-white shadow-[0_12px_24px_rgba(76,175,122,0.24)] transition hover:brightness-105 disabled:cursor-not-allowed disabled:opacity-45" },
  { id: "task", group: "form", label: "개인 할 일 추가", role: "primary", source: "src/components/plan-screen.tsx:662", location: "계획 / 개인 할 일 폼", width: "full", declaredFont: "13px / 600 (다른 분기: 14px)", className: "w-full rounded-[14px] bg-[var(--brand)] px-4 py-3 text-[13px] font-semibold text-white shadow-[0_8px_18px_rgba(121,184,149,0.16)] disabled:opacity-70" },
  { id: "save", group: "form", label: "저장", role: "primary", source: "src/components/plan-screen.tsx:713", location: "계획 / 할 일 편집", width: "content", declaredFont: "14px / 600", className: "rounded-[14px] bg-[var(--brand)] px-4 py-3 text-sm font-semibold text-white" },
  { id: "cancel", group: "form", label: "취소", role: "secondary", source: "src/components/plan-screen.tsx:723", location: "계획 / 할 일 편집", width: "content", declaredFont: "14px / 600", className: "rounded-[14px] border border-slate-200 bg-white px-4 py-3 text-sm font-semibold text-slate-600" },
  { id: "modal-save", group: "form", label: "저장하기", role: "primary", source: "src/components/study-rules-modal.tsx:124", location: "규칙 모달 / 하단", width: "flex-1 / 균등 분할", declaredFont: "14px / 600", className: "flex-1 rounded-[14px] bg-[var(--brand)] px-4 py-3 text-sm font-semibold text-white disabled:opacity-70" },
  { id: "leave", group: "form", label: "나가기", role: "danger", source: "src/components/group-home-screen.tsx:1122", location: "그룹 / 탈퇴 모달", width: "flex-1 / 균등 분할", declaredFont: "14px / 600", className: "flex-1 rounded-[16px] bg-rose-600 px-4 py-3 text-sm font-semibold text-white disabled:opacity-70" },
  { id: "create", group: "form", label: "모임 생성하기", role: "primary", source: "src/components/study-create-screen.tsx:114", location: "모임 생성 / 폼 하단", width: "full", declaredFont: "14px / 600", className: "w-full rounded-2xl bg-[var(--brand)] px-4 py-3 text-sm font-semibold text-white shadow-[0_18px_40px_rgba(121,184,149,0.24)] transition hover:brightness-105 disabled:opacity-70" },
  { id: "login", group: "tall", label: "로그인", role: "primary", source: "src/app/login/page.tsx:159", location: "로그인 / 폼 하단", width: "full", declaredFont: "16px / 600", className: "inline-flex w-full items-center justify-center rounded-[18px] bg-[var(--brand)] px-4 py-4 text-base font-semibold text-white shadow-[0_14px_28px_rgba(121,184,149,0.22)] transition hover:brightness-[0.98] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--brand)] focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:bg-[rgba(121,184,149,0.55)] disabled:shadow-none" },
  { id: "account", group: "tall", label: "계정 바꾸기", role: "secondary", source: "src/app/login/page.tsx:110", location: "로그인 / 계정 확인", width: "부모 grid stretch", declaredFont: "16px / 600", className: "inline-flex items-center justify-center rounded-[18px] border border-slate-200 bg-white px-4 py-4 text-base font-semibold text-slate-700 transition hover:bg-slate-50" },
];
